/**
 * Copyright (c) Kitimi Platforms and affiliates.
 *
 * Kitiplex - The hub for contributors, authors, and maintainers in the Kitimi ecosystem.
 * Licensed under MIT. See LICENSE file in the root directory.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  community: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

export default sidebars;
