/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  development: [

    'intro',
    
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      link: {
        type: 'generated-index',
      },
      items: [
        'development/guides/installing-python',
        'development/guides/openai-api',
        'development/guides/wsl-kali',

      ]
    },
    {
      type: 'category',
      label: 'Gists',
      collapsed: false,
      link: {
        type: 'generated-index',

      },
      items:
      [
        'development/gists/browser-dev',
        'development/gists/pwsh-cli',
        'development/gists/live-editor',
        'development/gists/py-starters',
        'development/gists/celestial-distance',
      ]
    },
    {
      type: 'category',
      label: 'Nerds',
      collapsed: false,
      link: {
        type: 'generated-index',
        description: 'Nerds stuff.'
      },
      items:[
        'development/nerds/calculus',
        'development/nerds/mermaid-config'
      ]
    },
  ],

  projects: [

    'projects',

    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      link: {
        type: 'generated-index',
      },
      items: [
        'projects/basic/py-genesis',
        'projects/basic/this-website',
        'projects/basic/django-mono-repo',
        'projects/basic/ginabot-ai',
        'projects/basic/py-mono-repo',
      ]
    },

    {
      type:'category',
      label: 'Advanced',
      collapsed: false,
      link: {
        type: 'generated-index',
      },
      items:[
        'projects/advanced/advanced-proj',
        'projects/advanced/another-advanced'
      ]
    },
  ],
  policies: [
    
    {
      type: 'category',
      label: 'Policies',
      collapsed: false,
      link: {
        type: 'generated-index',
        description: "Engineers, developers, members, authors and future contributors, as we aim to create a welcoming, peaceful, friendly and inclusive community, are encouraged to foster collaboration, embrace diversity, and uphold a culture of mutual respect, ensuring that every individual's voice is valued and heard in our collective pursuit of innovation and shared success.",
      },
      items: [
        'guidelines/code-of-conduct',
        'guidelines/security-policy'
      ]
    }
  ],

  
  

};

export default sidebars;
